{
 "title": "Aptos Validator Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{},job)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, chain)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$instance:9100\"}, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{chain=~\"$chain\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeID",
    "label": "nodeID",
    "query": {
     "query": "label_values(aptos_connections{direction=\"inbound\"},peer_id)"
    }
   },
   {
    "name": "chainAPI",
    "query": {
     "query": "CollectionLookup(mainnet,mainnet.aptoslabs.com,llt,testnet.aptoslabs.com,preview,vfn-preview.aptos.rhinostake.com,$chain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Version",
   "type": "stat",
   "description": "Version reported by nodes",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{job=~\"${job}\",chain=~\"${chain}\",type=\"synced\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| project \"ledger_version\", \"ledger\"=tonumber(\"ledger_version\")\n| scope \"ledger\"",
     "url": "https://${chainAPI}/v1/",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Node Epoch",
   "type": "stat",
   "description": "Epoch reported by nodes",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{job=~\"${job}\",chain=~\"${chain}\",type=\"synced_epoch\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Status",
   "type": "stat",
   "description": "Consensus Data reported by nodes",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_epoch{job=~\"${job}\",chain=~\"${chain}\"}",
     "legendFormat": "Consensus Epoch"
    },
    {
     "expr": "aptos_consensus_current_round{job=~\"${job}\",chain=~\"${chain}\"}",
     "legendFormat": "Consensus Round"
    }
   ]
  },
  {
   "title": "Vals in Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_current_epoch_validators{job=~\"${job}\",chain=~\"${chain}\"}"
    }
   ]
  },
  {
   "title": "Epoch Ends At",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "source": "url",
     "type": "uql",
     "uql": "parse-json\n| jsonata \"data.last_reconfiguration_time\"",
     "url": "https://${chainAPI}/v1/accounts/0x1/resources",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Txns Since Restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"}"
    }
   ]
  },
  {
   "title": "Current Txn Rate",
   "type": "stat",
   "description": "Transactions per second (5m average)",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=~\"success\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed/Retried Txn %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=~\"retry|failed\"}) / sum(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal Rate",
   "type": "stat",
   "description": "Proposals per minute over the last 5 minutes",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[5m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposals Sent",
   "type": "stat",
   "description": "Proposals sent by validator",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "increase(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[1h])",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "increase(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[6h])",
     "legendFormat": "Last 6h"
    },
    {
     "expr": "increase(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[24h])",
     "legendFormat": "Last 1d"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "stat",
   "description": "Failures per minute over the last 5 minutes",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[5m])",
     "legendFormat": "Last 5m"
    }
   ]
  },
  {
   "title": "Failed Proposals",
   "type": "stat",
   "description": "Failed proposals in window from validator over period",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[15m]))",
     "legendFormat": "Last 15m"
    },
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[1h]))",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[6h]))",
     "legendFormat": "Last 6h"
    },
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[24h]))",
     "legendFormat": "Last 1d"
    },
    {
     "expr": "sum(increase(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[7d]))",
     "legendFormat": "Last 7d"
    }
   ]
  },
  {
   "title": "Val Participation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(aptos_chain_health_participating_voting_power_last_100_rounds{job=~\"${job}\",chain=~\"${chain}\"})/(aptos_chain_health_total_voting_power{job=~\"${job}\",chain=~\"${chain}\"})",
     "legendFormat": "Voting Power"
    },
    {
     "expr": "(aptos_chain_health_participating_num_validators_last_100_rounds{job=~\"${job}\",chain=~\"${chain}\"})/(aptos_chain_health_total_num_validators{job=~\"${job}\",chain=~\"${chain}\"})",
     "legendFormat": "Validators"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "stat",
   "description": "Peer connections",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aptos_connections{job=~\"$job\",chain=~\"${chain}\",role_type=\"validator\",network_id=\"Validator\",network_id!=\"vfn\"})",
     "legendFormat": "Val Connections"
    },
    {
     "expr": "sum(aptos_connections{job=~\"$job\",chain=~\"${chain}\",role_type=\"full_node\",network_id!=\"vfn\"})",
     "legendFormat": "VFN Connections"
    }
   ]
  },
  {
   "title": "VFN Connected?",
   "type": "stat",
   "description": "Captures if the full node is connected.  Network ID in config file must be `vfn`.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aptos_connections{job=~\"$job\",chain=~\"${chain}\",network_id=\"vfn\",role_type=\"validator\"})",
     "legendFormat": "Inbound - {{instance}}"
    }
   ]
  },
  {
   "title": "Server Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",chain=~\"$chain\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\",chain=~\"$chain\"}) by (instance)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",chain=~\"$chain\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",chain=~\"$chain\"}) by (instance) /8",
     "legendFormat": "Cores"
    },
    {
     "expr": "node_load5{job=~\"$job\",chain=~\"$chain\"}",
     "legendFormat": "5m load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",chain=~\"$chain\",mode=\"idle\"}[$__interval])) by (instance)) * 100",
     "legendFormat": "CPU used%"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\",chain=~\"$chain\"} / (node_memory_MemTotal_bytes{job=~\"$job\",chain=~\"$chain\"}))) * 100",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\",chain=~\"$chain\"}[$__interval])) by (instance)",
     "legendFormat": "Disk read%"
    },
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{job=~\"$job\",chain=~\"$chain\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}/node_filesystem_size_bytes{job=~\"$job\",chain=~\"$chain\",mountpoint=~\"/\",fstype=~\"ext.?|xfs\"}) by (instance)) * 100",
     "legendFormat": "/ used%"
    },
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{job=~\"$job\",chain=~\"$chain\",mountpoint=~\"/home\",fstype=~\"ext.?|xfs\"}/node_filesystem_size_bytes{job=~\"$job\",chain=~\"$chain\",mountpoint=~\"/home\",fstype=~\"ext.?|xfs\"}) by (instance)) * 100",
     "legendFormat": "/home used%"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\",chain=~\"$chain\"}[$__interval])) by (instance)",
     "legendFormat": "Disk write%"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\",chain=~\"$chain\"}[$__interval])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\",chain=~\"$chain\"}[$__interval])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  { "title": "Liveness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Check Status",
   "type": "stat",
   "description": "This utilizes a prometheus endpoint from checkly.com.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "checkly_check_degraded_status{tags=~\"^(.*?)${chain}(.*?)\"}",
     "legendFormat": "{{check_name}}"
    }
   ]
  },
  {
   "title": "API Test Last Results (ms)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (check_name) (checkly_check_result{tags=~\"^(.*?)${chain}(.*?)\"})",
     "legendFormat": "{{check_name}}"
    }
   ]
  },
  { "title": "API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(caddy_http_request_duration_seconds_count{handler=\"subroute\", chain=~\"${chain}\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests by Response Code (%)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(irate(caddy_http_request_duration_seconds_count{handler=\"subroute\",chain=~\"${chain}\"}[1m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"subroute\",chain=~\"${chain}\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"subroute\",chain=~\"${chain}\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"subroute\",chain=~\"${chain}\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"subroute\",chain=~\"${chain}\"}[1m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{handler=\"subroute\",chain=~\"${chain}\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request Duration (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{handler=\"subroute\",chain=~\"${chain}\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Validator Connections (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_connections{job=~\"$job\",chain=~\"${chain}\",direction=\"inbound\",role_type=\"validator\",network_id=\"Validator\"}",
     "legendFormat": "Inbound - {{instance}}"
    },
    {
     "expr": "aptos_connections{job=~\"$job\",chain=~\"${chain}\",direction=\"outbound\",role_type=\"validator\",network_id=\"Validator\"}",
     "legendFormat": "Outbound - {{instance}}"
    },
    {
     "expr": "sum(aptos_connections{job=~\"$job\",chain=~\"${chain}\",role_type=\"validator\",network_id=\"Validator\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Full Node Connections (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_connections{job=~\"$job\",chain=~\"${chain}\",direction=\"inbound\",role_type=\"full_node\",network_id!=\"vfn\"}",
     "legendFormat": "Inbound - {{instance}}"
    },
    {
     "expr": "aptos_connections{job=~\"$job\",chain=~\"${chain}\",direction=\"outbound\",role_type=\"full_node\",network_id!=\"vfn\"}",
     "legendFormat": "Outbound - {{instance}}"
    },
    {
     "expr": "sum(aptos_connections{job=~\"$job\",chain=~\"${chain}\",role_type=\"full_node\",network_id!=\"vfn\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Committed and Failed Proposals in Window",
   "type": "timeseries",
   "description": "Failed proposals in window for this validator",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(aptos_committed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"})",
     "legendFormat": "Committed - $instance"
    },
    {
     "expr": "(aptos_failed_proposals_in_window{job=\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"})",
     "legendFormat": "Failures - $instance"
    },
    {
     "expr": "aptos_consensus_current_round{job=~\"${job}\",chain=~\"${chain}\"}",
     "legendFormat": "Round"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1 / rate(aptos_consensus_committed_blocks_count{job=\"${job}\",chain=~\"${chain}\"}[5m])",
     "legendFormat": "Block Time - {{instance}}"
    },
    {
     "expr": "1 / rate(aptos_consensus_committed_blocks_count{job=\"${job}\",chain=~\"${chain}\"}[6h])",
     "legendFormat": "Block Time - 6hr avg"
    },
    {
     "expr": "1 / rate(aptos_consensus_committed_blocks_count{job=\"${job}\",chain=~\"${chain}\"}[24h])",
     "legendFormat": "Block Time - 24hr avg"
    }
   ]
  },
  {
   "title": "Proposals Sent By Validator / min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[15m]) * 60",
     "legendFormat": "Proposals /min - $instance"
    },
    {
     "expr": "rate(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[6h]) * 60",
     "legendFormat": "Proposals /min - 6hr avg"
    },
    {
     "expr": "rate(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[1d]) * 60",
     "legendFormat": "Proposals /min - 24hr avg"
    },
    {
     "expr": "(increase(aptos_consensus_proposals_count{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}[45s]))",
     "legendFormat": "Proposal Sent"
    }
   ]
  },
  {
   "title": "Consensus Rounds /sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_last_committed_round{job=~\"${job}\",chain=~\"${chain}\"}[1m])",
     "legendFormat": "Rounds /sec"
    },
    {
     "expr": "1/(rate(aptos_consensus_last_committed_round{job=~\"${job}\",chain=~\"${chain}\"}[1m]))",
     "legendFormat": "Block time"
    }
   ]
  },
  {
   "title": "Validator Participation (last 100 rounds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(aptos_chain_health_participating_voting_power_last_100_rounds{job=~\"${job}\",chain=~\"${chain}\"})/(aptos_chain_health_total_voting_power{job=~\"${job}\",chain=~\"${chain}\"})",
     "legendFormat": "Participating Voting Power"
    },
    {
     "expr": "(aptos_chain_health_participating_num_validators_last_100_rounds{job=~\"${job}\",chain=~\"${chain}\"})/(aptos_chain_health_total_num_validators{job=~\"${job}\",chain=~\"${chain}\"})",
     "legendFormat": "Participating Validators"
    }
   ]
  },
  {
   "title": "Schema get() Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(aptos_schemadb_get_latency_seconds_sum{job=~\"${job}\",chain=~\"${chain}\"}[1m])) / sum by (instance) (irate(aptos_schemadb_get_latency_seconds_count{job=~\"${job}\",chain=~\"${chain}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions /sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"}[5m])",
     "legendFormat": "Transactions /sec {{instance}}"
    },
    {
     "expr": "rate(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"}[6h])",
     "legendFormat": "Transactions /sec - 6hr avg"
    },
    {
     "expr": "rate(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"}[1d])",
     "legendFormat": "Transactions /sec - 24hr avg"
    }
   ]
  },
  {
   "title": "Txn Totals",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"}[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "increase(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"}[1h])",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "increase(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"}[6h])",
     "legendFormat": "Last 6h"
    },
    {
     "expr": "increase(aptos_consensus_committed_txns_count{job=~\"${job}\",chain=~\"${chain}\",state=\"success\"}[1d])",
     "legendFormat": "Last 1d"
    }
   ]
  },
  {
   "title": "Consensus Time Distribution",
   "type": "timeseries",
   "description": "A stacked chart of time spent in each part of the \"production pipeline\"",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{job=~\"${job}\",chain=~\"${chain}\"}[1m])",
     "legendFormat": "{{op}}"
    },
    {
     "expr": "sum(rate(consensus_duration_sum{job=~\"${job}\",chain=~\"${chain}\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "mempool index size",
   "type": "timeseries",
   "description": "Size of a core mempool index",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "aptos_core_mempool_index_size{job=~\"${job}\",instance=~\"${instance}.*\",chain=~\"${chain}\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Block Commit Time Distribution (s)",
   "type": "bargauge",
   "description": "The total time spent in seconds of commiting blocks in Aptos executor ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_executor_commit_blocks_seconds_bucket{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block Execute Time Distribution (s)",
   "type": "bargauge",
   "description": "The total time spent in seconds of block execution in the block executor.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_executor_execute_block_seconds_bucket{job=~\"${job}\",chain=~\"${chain}\",instance=~\"${instance}.*\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Network Consensus Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_error_count{chain=~\"${chain}\"}[5m])",
     "legendFormat": "{{chain}} consensus errors /min"
    }
   ]
  },
  {
   "title": "Node Information for $hostname ($instance) - based on instance selection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 93 }, "options": { "content": "# ${hostname} (${instance})" } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$instance:.*\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance:.*\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$instance:.*\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$instance:.*\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=~\"$instance:.*\",job=\"$job\"}) / count(count(node_cpu_seconds_total{instance=~\"$instance:.*\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance:.*\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$instance:.*\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Home FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/home\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/home\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance:.*\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance:.*\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "HomeFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance:.*\",job=\"$job\",mountpoint=\"/home\",fstype!=\"rootfs\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$instance:.*\",job=\"$job\"} - node_boot_time_seconds{instance=~\"$instance:.*\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\"nice|steal\",instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} - node_memory_MemFree_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} - (node_memory_Cached_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance:.*\",chain=~\"$chain\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance:.*\",chain=~\"$chain\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance:.*\",chain=~\"$chain\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Disk R/W (kb/sec by device)",
   "type": "timeseries",
   "description": "The number of kibibytes read and written to the device  per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device!~\"md.*\",chain=~\"$chain\",instance=~\"$instance:.*\"}[$interval])",
     "legendFormat": "{{device}} Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device!~\"md.*\",chain=~\"$chain\",instance=~\"$instance:.*\"}[$interval])",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  {
   "title": "Disk R/W (Requests/sec by device)",
   "type": "timeseries",
   "description": "The number of kibibytes read and written to the device  per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device!~\"md.*\",chain=~\"$chain\",instance=~\"$instance:.*\"}[$interval])",
     "legendFormat": "{{device}} Read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device!~\"md.*\",chain=~\"$chain\",instance=~\"$instance:.*\"}[$interval])",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  {
   "title": "Disk CPU Utilization (%)",
   "type": "timeseries",
   "description": "The percent of CPU time during which I/O requests were issued to the device",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$interval])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk Latencies",
   "type": "timeseries",
   "description": "Time spent on each read/write operation (ignores individual \"md\" devices)",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__interval]) / rate(node_disk_reads_completed_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__interval])",
     "legendFormat": "{{device}} Read Latency"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__interval]) / rate(node_disk_writes_completed_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__interval])",
     "legendFormat": "{{device}} Write Latency"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__interval])",
     "legendFormat": "{{device}} IO Time"
    },
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=~\"$instance:.*\",chain=~\"$chain\",device!~\"md.*\"}[$__interval])",
     "legendFormat": "{{device}} IO Weighted"
    }
   ]
  },
  {
   "title": "Disk Space (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance:.*\",chain=~\"$chain\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Data Last Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[24h]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[24h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Open  File Descriptor (left) / Context switches (right)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance:.*\",chain=~\"$chain\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance:.*\",chain=~\"$chain\"}[$interval])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Data Last Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$instance:.*\"}[7d]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$instance:.*\"}[7d]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Data Last Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$instance:.*\"}[31d]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$instance:.*\"}[31d]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}